version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-php-framework:latest
    container_name: php-framework-server
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge